-- Katalog beasiswa luar negeri tambahan yang terbuka untuk WNI. Hanya nama, penyelenggara, negara, dan
-- URL resmi yang diisi; tanggal, syarat, pendanaan, jenjang, dan riwayat siklus diisi mesin riset
-- otomatis (research-opportunities) dari sumber resmi berkutipan. Status awal "upcoming" + needs_review
-- sampai riset menerapkan fakta resmi.

insert into public.organizations (name, normalized_name, slug, kind, country_code, website) values
  ('Kedutaan Besar Jepang di Indonesia (MEXT)', 'kedutaan besar jepang di indonesia mext', 'kedubes-jepang-mext', 'government', 'JP', 'https://www.id.emb-japan.go.jp'),
  ('Manaaki New Zealand Scholarships', 'manaaki new zealand scholarships', 'manaaki-nz', 'government', 'NZ', 'https://www.nzscholarships.govt.nz'),
  ('Swedish Institute', 'swedish institute', 'swedish-institute', 'government', 'SE', 'https://si.se'),
  ('Campus China (China Scholarship Council)', 'campus china china scholarship council', 'campus-china-csc', 'government', 'CN', 'https://www.campuschina.org'),
  ('TaiwanICDF', 'taiwanicdf', 'taiwan-icdf', 'government', 'TW', 'https://www.icdf.org.tw'),
  ('SERI (Pemerintah Swiss)', 'seri pemerintah swiss', 'seri-swiss', 'government', 'CH', 'https://www.sbfi.admin.ch'),
  ('Campus France', 'campus france', 'campus-france', 'government', 'FR', 'https://www.campusfrance.org'),
  ('Gates Cambridge Trust', 'gates cambridge trust', 'gates-cambridge', 'foundation', 'GB', 'https://www.gatescambridge.org'),
  ('University of Oxford (Clarendon Fund)', 'university of oxford clarendon fund', 'oxford-clarendon', 'university', 'GB', 'https://www.ox.ac.uk'),
  ('Bank Dunia (World Bank)', 'bank dunia world bank', 'world-bank', 'other', null, 'https://www.worldbank.org'),
  ('Asian Development Bank', 'asian development bank', 'adb', 'other', null, 'https://www.adb.org'),
  ('Stanford University (Knight-Hennessy)', 'stanford university knight hennessy', 'stanford-knight-hennessy', 'university', 'US', 'https://knight-hennessy.stanford.edu'),
  ('Schwarzman Scholars', 'schwarzman scholars', 'schwarzman-scholars', 'foundation', 'CN', 'https://www.schwarzmanscholars.org'),
  ('Kementerian Pendidikan Singapura (MOE)', 'kementerian pendidikan singapura moe', 'moe-singapore', 'government', 'SG', 'https://www.moe.gov.sg'),
  ('Rotary International', 'rotary international', 'rotary-international', 'foundation', null, 'https://www.rotary.org')
on conflict (normalized_name) do nothing;

insert into public.opportunities
  (kind, tracks, title, slug, organization_id, country_code, region, summary, funding, study_levels,
   apply_url, official_url, closes_at, status, verification_status, confidence, attributes, dedupe_key, is_rolling)
values
  ('scholarship', '{scholarship}', 'Beasiswa MEXT (Monbukagakusho) Jepang', 'mext-jepang',
   (select id from public.organizations where normalized_name = 'kedutaan besar jepang di indonesia mext'), 'JP', null,
   'Beasiswa Pemerintah Jepang (MEXT) yang diseleksi lewat Kedutaan Besar Jepang di Indonesia untuk beberapa program (mis. riset/pascasarjana, S1, D3, dan sekolah kejuruan).',
   null, '{}', 'https://www.id.emb-japan.go.jp/sch.html', 'https://www.id.emb-japan.go.jp/sch.html', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:mext-jepang', false),
  ('scholarship', '{scholarship}', 'Manaaki New Zealand Scholarships', 'manaaki-new-zealand',
   (select id from public.organizations where normalized_name = 'manaaki new zealand scholarships'), 'NZ', null,
   'Beasiswa Pemerintah Selandia Baru untuk warga negara berkembang yang memenuhi syarat, termasuk studi di universitas Selandia Baru.',
   null, '{}', 'https://www.nzscholarships.govt.nz/', 'https://www.nzscholarships.govt.nz/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:manaaki-new-zealand', false),
  ('scholarship', '{scholarship}', 'Swedish Institute Scholarships for Global Professionals', 'si-global-professionals',
   (select id from public.organizations where normalized_name = 'swedish institute'), 'SE', null,
   'Beasiswa Swedish Institute untuk profesional dari negara tertentu yang ingin menempuh magister di Swedia.',
   null, '{}', 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/', 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:si-global-professionals', false),
  ('scholarship', '{scholarship}', 'Chinese Government Scholarship (CSC)', 'chinese-government-scholarship',
   (select id from public.organizations where normalized_name = 'campus china china scholarship council'), 'CN', null,
   'Beasiswa Pemerintah Tiongkok yang dikelola China Scholarship Council, dengan beberapa jalur pendaftaran (kedutaan, universitas, dan program khusus).',
   null, '{}', 'https://www.campuschina.org/', 'https://www.campuschina.org/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:chinese-government-scholarship', false),
  ('scholarship', '{scholarship}', 'TaiwanICDF International Higher Education Scholarship', 'taiwan-icdf',
   (select id from public.organizations where normalized_name = 'taiwanicdf'), 'TW', null,
   'Beasiswa TaiwanICDF untuk mahasiswa dari negara mitra yang memenuhi syarat, untuk program berbahasa Inggris di universitas Taiwan.',
   null, '{}', 'https://www.icdf.org.tw/', 'https://www.icdf.org.tw/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:taiwan-icdf', false),
  ('scholarship', '{scholarship}', 'Swiss Government Excellence Scholarships', 'swiss-government-excellence',
   (select id from public.organizations where normalized_name = 'seri pemerintah swiss'), 'CH', null,
   'Beasiswa Pemerintah Swiss untuk peneliti asing (riset, doktor, dan pascadoktoral) di universitas publik Swiss.',
   null, '{}', 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html', 'https://www.sbfi.admin.ch/sbfi/en/home/education/scholarships-and-grants/swiss-government-excellence-scholarships.html', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:swiss-government-excellence', false),
  ('scholarship', '{scholarship}', 'Eiffel Excellence Scholarship (Prancis)', 'eiffel-excellence',
   (select id from public.organizations where normalized_name = 'campus france'), 'FR', null,
   'Beasiswa Kementerian Luar Negeri Prancis untuk mahasiswa internasional magister dan doktor; pencalonan dilakukan oleh institusi Prancis.',
   null, '{}', 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence', 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:eiffel-excellence', false),
  ('scholarship', '{scholarship}', 'Gates Cambridge Scholarship', 'gates-cambridge',
   (select id from public.organizations where normalized_name = 'gates cambridge trust'), 'GB', null,
   'Beasiswa untuk pascasarjana di University of Cambridge bagi pendaftar dari luar Inggris.',
   null, '{}', 'https://www.gatescambridge.org/', 'https://www.gatescambridge.org/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:gates-cambridge', false),
  ('scholarship', '{scholarship}', 'Clarendon Scholarships (University of Oxford)', 'clarendon-oxford',
   (select id from public.organizations where normalized_name = 'university of oxford clarendon fund'), 'GB', null,
   'Beasiswa pascasarjana University of Oxford; pendaftar otomatis dipertimbangkan saat mendaftar program studi pada tenggat tertentu.',
   null, '{}', 'https://www.ox.ac.uk/clarendon', 'https://www.ox.ac.uk/clarendon', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:clarendon-oxford', false),
  ('scholarship', '{scholarship}', 'Joint Japan/World Bank Graduate Scholarship Program (JJ/WBGSP)', 'jj-wbgsp',
   (select id from public.organizations where normalized_name = 'bank dunia world bank'), null, 'Berbagai negara',
   'Beasiswa magister Bank Dunia dan Pemerintah Jepang untuk profesional di bidang pembangunan dari negara anggota yang memenuhi syarat.',
   null, '{}', 'https://www.worldbank.org/en/programs/scholarships', 'https://www.worldbank.org/en/programs/scholarships', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:jj-wbgsp', false),
  ('scholarship', '{scholarship}', 'ADB–Japan Scholarship Program (ADB-JSP)', 'adb-jsp',
   (select id from public.organizations where normalized_name = 'asian development bank'), null, 'Asia-Pasifik',
   'Beasiswa Asian Development Bank dan Pemerintah Jepang untuk pascasarjana di institusi mitra di kawasan Asia-Pasifik.',
   null, '{}', 'https://www.adb.org/work-with-us/careers/japan-scholarship-program', 'https://www.adb.org/work-with-us/careers/japan-scholarship-program', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:adb-jsp', false),
  ('scholarship', '{scholarship}', 'Knight-Hennessy Scholars (Stanford)', 'knight-hennessy',
   (select id from public.organizations where normalized_name = 'stanford university knight hennessy'), 'US', null,
   'Beasiswa pascasarjana Stanford University untuk semua program studi, terbuka bagi pendaftar dari seluruh dunia.',
   null, '{}', 'https://knight-hennessy.stanford.edu/', 'https://knight-hennessy.stanford.edu/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:knight-hennessy', false),
  ('scholarship', '{scholarship}', 'Schwarzman Scholars (Tsinghua University)', 'schwarzman-scholars',
   (select id from public.organizations where normalized_name = 'schwarzman scholars'), 'CN', null,
   'Program magister satu tahun di Tsinghua University, Beijing, terbuka bagi pendaftar dari seluruh dunia.',
   null, '{}', 'https://www.schwarzmanscholars.org/', 'https://www.schwarzmanscholars.org/', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:schwarzman-scholars', false),
  ('scholarship', '{scholarship}', 'ASEAN Undergraduate Scholarship (Singapura)', 'asean-undergraduate-singapore',
   (select id from public.organizations where normalized_name = 'kementerian pendidikan singapura moe'), 'SG', null,
   'Beasiswa Kementerian Pendidikan Singapura untuk warga negara ASEAN yang memenuhi syarat untuk studi S1 di universitas Singapura.',
   null, '{bachelor}', 'https://www.moe.gov.sg/financial-matters/awards-scholarships/asean-undergraduate-scholarship', 'https://www.moe.gov.sg/financial-matters/awards-scholarships/asean-undergraduate-scholarship', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:asean-undergraduate-singapore', false),
  ('scholarship', '{scholarship}', 'Rotary Peace Fellowship', 'rotary-peace-fellowship',
   (select id from public.organizations where normalized_name = 'rotary international'), null, 'Berbagai negara',
   'Fellowship Rotary untuk magister atau sertifikat profesional di bidang perdamaian dan pembangunan di Rotary Peace Centers.',
   null, '{}', 'https://www.rotary.org/en/our-programs/peace-fellowships', 'https://www.rotary.org/en/our-programs/peace-fellowships', null,
   'upcoming', 'needs_review', 30, '{"seed":true,"catalog":"v2"}', 'seed:rotary-peace-fellowship', false)
on conflict (slug) do nothing;
