-- Karir Pro — data referensi awal (track, negara, jenis dokumen)

insert into public.tracks (code, name, description, sort_order) values
  ('whv_au', 'WHV Australia', 'Work and Holiday visa (subclass 462) dan lowongan untuk pemegang WHV.', 1),
  ('dama_au', 'DAMA Australia', 'Pekerjaan bersponsor lewat Designated Area Migration Agreement.', 2),
  ('professional', 'Kerja Profesional', 'Lowongan profesional di luar negeri, termasuk yang menyediakan sponsor visa.', 3),
  ('overseas', 'Kerja Luar Negeri', 'Program resmi (G-to-G, SSW, EPS) serta lowongan hospitality, kapal pesiar, dan lainnya.', 4),
  ('scholarship', 'Beasiswa', 'Beasiswa populer untuk WNI: LPDP, AAS, Erasmus Mundus, Chevening, DAAD, GKS, dan lainnya.', 5);

insert into public.countries (code, name_id, name_en, flag, currency, region) values
  ('ID', 'Indonesia', 'Indonesia', '🇮🇩', 'IDR', 'Asia'),
  ('AU', 'Australia', 'Australia', '🇦🇺', 'AUD', 'Oseania'),
  ('NZ', 'Selandia Baru', 'New Zealand', '🇳🇿', 'NZD', 'Oseania'),
  ('JP', 'Jepang', 'Japan', '🇯🇵', 'JPY', 'Asia'),
  ('KR', 'Korea Selatan', 'South Korea', '🇰🇷', 'KRW', 'Asia'),
  ('TW', 'Taiwan', 'Taiwan', '🇹🇼', 'TWD', 'Asia'),
  ('SG', 'Singapura', 'Singapore', '🇸🇬', 'SGD', 'Asia'),
  ('MY', 'Malaysia', 'Malaysia', '🇲🇾', 'MYR', 'Asia'),
  ('HK', 'Hong Kong', 'Hong Kong', '🇭🇰', 'HKD', 'Asia'),
  ('CN', 'Tiongkok', 'China', '🇨🇳', 'CNY', 'Asia'),
  ('AE', 'Uni Emirat Arab', 'United Arab Emirates', '🇦🇪', 'AED', 'Timur Tengah'),
  ('SA', 'Arab Saudi', 'Saudi Arabia', '🇸🇦', 'SAR', 'Timur Tengah'),
  ('QA', 'Qatar', 'Qatar', '🇶🇦', 'QAR', 'Timur Tengah'),
  ('TR', 'Turki', 'Türkiye', '🇹🇷', 'TRY', 'Eropa'),
  ('GB', 'Inggris Raya', 'United Kingdom', '🇬🇧', 'GBP', 'Eropa'),
  ('IE', 'Irlandia', 'Ireland', '🇮🇪', 'EUR', 'Eropa'),
  ('DE', 'Jerman', 'Germany', '🇩🇪', 'EUR', 'Eropa'),
  ('NL', 'Belanda', 'Netherlands', '🇳🇱', 'EUR', 'Eropa'),
  ('FR', 'Prancis', 'France', '🇫🇷', 'EUR', 'Eropa'),
  ('BE', 'Belgia', 'Belgium', '🇧🇪', 'EUR', 'Eropa'),
  ('CH', 'Swiss', 'Switzerland', '🇨🇭', 'CHF', 'Eropa'),
  ('AT', 'Austria', 'Austria', '🇦🇹', 'EUR', 'Eropa'),
  ('SE', 'Swedia', 'Sweden', '🇸🇪', 'SEK', 'Eropa'),
  ('NO', 'Norwegia', 'Norway', '🇳🇴', 'NOK', 'Eropa'),
  ('FI', 'Finlandia', 'Finland', '🇫🇮', 'EUR', 'Eropa'),
  ('DK', 'Denmark', 'Denmark', '🇩🇰', 'DKK', 'Eropa'),
  ('HU', 'Hongaria', 'Hungary', '🇭🇺', 'HUF', 'Eropa'),
  ('PL', 'Polandia', 'Poland', '🇵🇱', 'PLN', 'Eropa'),
  ('IT', 'Italia', 'Italy', '🇮🇹', 'EUR', 'Eropa'),
  ('ES', 'Spanyol', 'Spain', '🇪🇸', 'EUR', 'Eropa'),
  ('US', 'Amerika Serikat', 'United States', '🇺🇸', 'USD', 'Amerika'),
  ('CA', 'Kanada', 'Canada', '🇨🇦', 'CAD', 'Amerika');

insert into public.document_types (code, name, category, has_expiry, is_sensitive, description, sort_order) values
  ('passport', 'Paspor', 'identitas', true, true, 'Paspor RI yang masih berlaku; banyak program mensyaratkan masa berlaku minimal 6 bulan.', 1),
  ('ktp', 'KTP', 'identitas', false, true, 'Kartu Tanda Penduduk.', 2),
  ('kk', 'Kartu Keluarga', 'identitas', false, true, null, 3),
  ('birth_certificate', 'Akta Kelahiran', 'identitas', false, true, null, 4),
  ('diploma', 'Ijazah', 'pendidikan', false, false, 'Ijazah pendidikan terakhir.', 10),
  ('transcript', 'Transkrip Nilai', 'pendidikan', false, false, null, 11),
  ('diploma_legalized', 'Legalisasi Ijazah & Transkrip', 'pendidikan', false, false, 'Legalisasi dari kampus atau instansi terkait.', 12),
  ('sworn_translation', 'Terjemahan Tersumpah', 'legal', false, false, 'Terjemahan dokumen oleh penerjemah tersumpah.', 13),
  ('loa', 'Letter of Acceptance (LoA)', 'pendidikan', true, false, 'Surat penerimaan dari universitas.', 14),
  ('ielts', 'Sertifikat IELTS', 'bahasa', true, false, 'Umumnya berlaku 2 tahun sejak tanggal tes.', 20),
  ('toefl_ibt', 'Sertifikat TOEFL iBT', 'bahasa', true, false, 'Umumnya berlaku 2 tahun sejak tanggal tes.', 21),
  ('pte', 'Sertifikat PTE Academic', 'bahasa', true, false, 'Umumnya berlaku 2 tahun sejak tanggal tes.', 22),
  ('toefl_itp', 'Sertifikat TOEFL ITP', 'bahasa', true, false, 'Diterima oleh sebagian beasiswa dalam negeri.', 23),
  ('topik', 'Sertifikat TOPIK / EPS-TOPIK', 'bahasa', true, false, 'Tes bahasa Korea.', 24),
  ('jlpt', 'Sertifikat JLPT / JFT-Basic', 'bahasa', true, false, 'Tes bahasa Jepang.', 25),
  ('german_cert', 'Sertifikat Bahasa Jerman (Goethe/telc)', 'bahasa', false, false, null, 26),
  ('cv', 'CV / Resume', 'karier', false, false, null, 30),
  ('motivation_letter', 'Motivation Letter / Personal Statement', 'karier', false, false, null, 31),
  ('recommendation_letter', 'Surat Rekomendasi', 'karier', false, false, null, 32),
  ('work_reference', 'Surat Keterangan Kerja / Paklaring', 'karier', false, false, null, 33),
  ('research_proposal', 'Proposal Riset', 'pendidikan', false, false, 'Umumnya untuk jenjang S3/riset.', 34),
  ('skck', 'SKCK', 'legal', true, true, 'Surat Keterangan Catatan Kepolisian (data pribadi spesifik).', 40),
  ('medical_checkup', 'Medical Check-up', 'kesehatan', true, true, 'Pemeriksaan kesehatan; beberapa negara mensyaratkan klinik yang ditunjuk (data pribadi spesifik).', 41),
  ('bank_statement', 'Rekening Koran / Bukti Dana', 'keuangan', true, true, 'Bukti kecukupan dana (data pribadi spesifik).', 42),
  ('rsa_certificate', 'Sertifikat RSA', 'sertifikat', false, false, 'Responsible Service of Alcohol (hospitality Australia).', 50),
  ('white_card', 'White Card', 'sertifikat', false, false, 'Sertifikat keselamatan konstruksi Australia.', 51),
  ('first_aid', 'Sertifikat First Aid', 'sertifikat', true, false, null, 52),
  ('food_safety', 'Sertifikat Food Safety / Food Handling', 'sertifikat', false, false, null, 53),
  ('driver_license', 'SIM / SIM Internasional', 'sertifikat', true, false, null, 54),
  ('seafarer_book', 'Buku Pelaut & Sertifikat BST', 'sertifikat', true, false, 'Untuk kerja di kapal pesiar/ABK.', 55);
