-- Sumber career page awal (status draft). Token diambil dari URL papan lowongan publik;
-- aktifkan hanya setelah uji kering (POST /api/ingest/run?drafts=1&dry_run=1) bersih.

insert into public.sources (slug, name, kind, authority, trust_score, tracks, country_code, base_url, config, schedule, status, terms_note)
values
  ('ats-greenhouse-agoda', 'Agoda (Greenhouse)', 'ats', 'employer', 85, '{professional}', null,
   'https://job-boards.greenhouse.io/agoda',
   '{"provider":"greenhouse","token":"agoda","company":"Agoda","group":"jobs"}', 'daily', 'draft',
   'API Job Board Greenhouse (publik). Sering menyebut relokasi.'),
  ('ats-greenhouse-vgw-australia', 'VGW Australia (Greenhouse)', 'ats', 'employer', 85, '{professional}', 'AU',
   'https://job-boards.greenhouse.io/vgw-australia',
   '{"provider":"greenhouse","token":"vgw-australia","company":"VGW","default_country":"AU","group":"jobs"}', 'daily', 'draft',
   'API Job Board Greenhouse (publik).'),
  ('ats-greenhouse-up', 'Up (Greenhouse)', 'ats', 'employer', 85, '{professional}', 'AU',
   'https://job-boards.greenhouse.io/up',
   '{"provider":"greenhouse","token":"up","company":"Up","default_country":"AU","group":"jobs"}', 'daily', 'draft',
   'API Job Board Greenhouse (publik).'),
  ('ats-greenhouse-lighthouse', 'Lighthouse (Greenhouse)', 'ats', 'employer', 85, '{professional}', null,
   'https://job-boards.greenhouse.io/lighthouse',
   '{"provider":"greenhouse","token":"lighthouse","company":"Lighthouse","group":"jobs"}', 'daily', 'draft',
   'API Job Board Greenhouse (publik).'),
  ('ats-greenhouse-ogilvyaus', 'Ogilvy Australia (Greenhouse)', 'ats', 'employer', 85, '{professional}', 'AU',
   'https://job-boards.greenhouse.io/ogilvyaus',
   '{"provider":"greenhouse","token":"ogilvyaus","company":"Ogilvy Australia","default_country":"AU","group":"jobs"}', 'daily', 'draft',
   'API Job Board Greenhouse (publik).'),
  ('ats-lever-shopback', 'ShopBack (Lever)', 'ats', 'employer', 85, '{professional}', null,
   'https://jobs.lever.co/shopback-2',
   '{"provider":"lever","token":"shopback-2","company":"ShopBack","group":"jobs"}', 'daily', 'draft',
   'API Postings Lever (publik).'),
  ('ats-lever-gotogroup', 'GoTo Group (Lever)', 'ats', 'employer', 85, '{professional}', 'ID',
   'https://jobs.lever.co/GoToGroup',
   '{"provider":"lever","token":"GoToGroup","company":"GoTo Group","default_country":"ID","group":"jobs"}', 'daily', 'draft',
   'API Postings Lever (publik).'),
  ('ats-lever-princesspolly', 'Princess Polly (Lever)', 'ats', 'employer', 85, '{professional,whv_au}', 'AU',
   'https://jobs.lever.co/princesspolly',
   '{"provider":"lever","token":"princesspolly","company":"Princess Polly","default_country":"AU","group":"jobs"}', 'daily', 'draft',
   'API Postings Lever (publik). Ritel/gudang: label WHV hanya bila iklan menyebut atau judulnya kerja kasual.'),
  ('ats-lever-upguard', 'UpGuard (Lever)', 'ats', 'employer', 85, '{professional}', null,
   'https://jobs.lever.co/upguard',
   '{"provider":"lever","token":"upguard","company":"UpGuard","group":"jobs"}', 'daily', 'draft',
   'API Postings Lever (publik). Iklan tertentu menyatakan tidak mendukung sponsor visa.'),
  ('ats-smartrecruiters-minor', 'Minor International (SmartRecruiters)', 'ats', 'employer', 85, '{overseas,professional}', null,
   'https://jobs.smartrecruiters.com/MinorInternational',
   '{"provider":"smartrecruiters","token":"MinorInternational","company":"Minor International","group":"jobs"}', 'daily', 'draft',
   'API Postings SmartRecruiters (publik). Jaringan hotel (Anantara, Avani, dll.) termasuk Australia/NZ/Asia.')
on conflict (slug) do nothing;
